name: CI/CD for Spring Boot with Docker Compose

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger workflow on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker images for services
      - name: Build and push app image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-system:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-system:latest

      - name: Build and push MySQL image (optional, if customized)
        run: |
          docker pull mysql:8.0  # Pulling the MySQL image
          docker tag mysql:8.0 ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest

      # Step 4: Deploy the application using Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
